MODEL:
  NAME: "Acme"
  INPUT_SIZE: 784
  NUM_CLASSES: 10

DATASET:
  NAME: "Acme"

WANDB:
  PROJECT_NAME: ""

CHECKPOINT:
  SAVE_EVERY: 10

OPTIMIZER:
  LR: 0.002
  LOSS: "MSELoss"

TRAIN:
  BATCH_SIZE: 32
  MAX_EPOCH: 300

EVAL:
  RUN_EVERY: 2
